import type { BusinessProfile } from "../../lib/business-profile-api";
import type { InvoiceDetail } from "../../lib/invoice-api";
import { centsToDollars } from "../../lib/invoice-api";
import { formatDate } from "../../lib/utils";

export type InvoiceTemplate = "modern" | "classic" | "minimal";

function fullAddress(profile: BusinessProfile): string {
  const parts = [
    profile.address_line1,
    profile.address_line2,
    profile.city,
    profile.state,
    profile.postal_code,
    profile.country,
  ].filter(Boolean);
  return parts.join(", ");
}

function statusLabel(status: string): string {
  const map: Record<string, string> = {
    draft: "Draft",
    sent: "Sent",
    paid: "Paid",
    overdue: "Overdue",
    cancelled: "Cancelled",
  };
  return map[status] ?? status;
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function printPageCss(): string {
  return `
@page {
  margin: 0.5in 0.5in 0.75in 0.5in;
  @top-left { content: ' '; }
  @top-center { content: ' '; }
  @top-right { content: ' '; }
  @bottom-left { content: ' '; }
  @bottom-center { content: ' '; }
  @bottom-right { content: counter(page); font-size: 9pt; color: #6b7280; font-family: system-ui, sans-serif; }
}
@media print {
  body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
}
`;
}

function footerHtml(): string {
  return `
<div style="margin-top: 48px; padding-top: 12px; border-top: 1px solid #e5e7eb; text-align: center; font-size: 11px; color: #9ca3af;">
  Generated by Taxeasy
</div>`;
}

export function generateInvoiceHtml(
  invoice: InvoiceDetail,
  profile: BusinessProfile,
  template: InvoiceTemplate,
  logoBase64?: string,
): string {
  const ctx = { invoice, profile, logoBase64 };
  switch (template) {
    case "classic":
      return classicTemplate(ctx);
    case "minimal":
      return minimalTemplate(ctx);
    default:
      return modernTemplate(ctx);
  }
}

function modernTemplate({
  invoice,
  profile,
  logoBase64,
}: {
  invoice: InvoiceDetail;
  profile: BusinessProfile;
  logoBase64?: string;
}): string {
  const addr = fullAddress(profile);
  const lines = invoice.lines
    .sort((a, b) => a.sort_order - b.sort_order)
    .map(
      (l) => `
      <tr>
        <td style="padding: 10px 16px; color: #1f2937; font-size: 13px;">${escapeHtml(l.description)}</td>
        <td style="padding: 10px 16px; text-align: right; color: #6b7280; font-size: 13px; font-variant-numeric: tabular-nums;">${l.quantity}</td>
        <td style="padding: 10px 16px; text-align: right; color: #6b7280; font-size: 13px; font-variant-numeric: tabular-nums;">$${centsToDollars(l.unit_price_cents)}</td>
        <td style="padding: 10px 16px; text-align: right; color: #1f2937; font-size: 13px; font-weight: 500; font-variant-numeric: tabular-nums;">$${centsToDollars(l.total_cents)}</td>
      </tr>`,
    )
    .join("");

  const logoImg = logoBase64
    ? `<img src="${logoBase64}" alt="Logo" style="max-width: 140px; max-height: 56px; object-fit: contain;" />`
    : "";

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title> </title>
<style>
  ${printPageCss()}
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: #111827; background: #fff; padding: 0; }
</style>
</head>
<body>
<div style="max-width: 800px; margin: 0 auto; padding: 40px 0;">
  <div style="display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 40px;">
    <div>
      ${logoImg ? `<div style="margin-bottom: 12px;">${logoImg}</div>` : ""}
      <div style="font-size: 22px; font-weight: 700; color: #111827;">${escapeHtml(profile.name)}</div>
      ${addr ? `<div style="font-size: 12px; color: #6b7280; margin-top: 4px;">${escapeHtml(addr)}</div>` : ""}
      ${profile.email ? `<div style="font-size: 12px; color: #6b7280; margin-top: 2px;">${escapeHtml(profile.email)}</div>` : ""}
      ${profile.phone ? `<div style="font-size: 12px; color: #6b7280; margin-top: 2px;">${escapeHtml(profile.phone)}</div>` : ""}
    </div>
    <div style="text-align: right;">
      <div style="font-size: 28px; font-weight: 700; color: #2563eb; text-transform: uppercase; letter-spacing: 0.05em;">${escapeHtml(invoice.invoice_type)}</div>
      <div style="font-size: 14px; color: #6b7280; margin-top: 8px;">${escapeHtml(invoice.invoice_number)}</div>
      <div style="display: inline-block; margin-top: 6px; padding: 3px 10px; border-radius: 4px; background: ${invoice.status === "paid" ? "#dcfce7" : invoice.status === "overdue" ? "#fee2e2" : "#eff6ff"}; color: ${invoice.status === "paid" ? "#166534" : invoice.status === "overdue" ? "#991b1b" : "#1e40af"}; font-size: 11px; font-weight: 600; text-transform: uppercase;">${statusLabel(invoice.status)}</div>
    </div>
  </div>

  <div style="display: flex; justify-content: space-between; margin-bottom: 32px;">
    <div style="flex: 1;">
      <div style="font-size: 10px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.08em; color: #9ca3af; margin-bottom: 6px;">Bill To</div>
      <div style="font-size: 14px; font-weight: 600; color: #111827;">${escapeHtml(invoice.client_name)}</div>
      ${invoice.client_email ? `<div style="font-size: 12px; color: #6b7280; margin-top: 2px;">${escapeHtml(invoice.client_email)}</div>` : ""}
      ${invoice.client_address ? `<div style="font-size: 12px; color: #6b7280; margin-top: 2px; white-space: pre-line;">${escapeHtml(invoice.client_address)}</div>` : ""}
    </div>
    <div style="text-align: right;">
      <div style="margin-bottom: 8px;">
        <span style="font-size: 10px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.08em; color: #9ca3af;">Issue Date</span><br/>
        <span style="font-size: 13px; color: #111827;">${formatDate(invoice.issue_date)}</span>
      </div>
      ${
        invoice.due_date
          ? `<div>
        <span style="font-size: 10px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.08em; color: #9ca3af;">Due Date</span><br/>
        <span style="font-size: 13px; color: ${invoice.status === "overdue" ? "#dc2626" : "#111827"}; font-weight: ${invoice.status === "overdue" ? "600" : "400"};">${formatDate(invoice.due_date)}</span>
      </div>`
          : ""
      }
    </div>
  </div>

  <table style="width: 100%; border-collapse: collapse; margin-bottom: 24px;">
    <thead>
      <tr style="background: #f9fafb;">
        <th style="padding: 10px 16px; text-align: left; font-size: 10px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.08em; color: #6b7280;">Description</th>
        <th style="padding: 10px 16px; text-align: right; font-size: 10px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.08em; color: #6b7280; width: 80px;">Qty</th>
        <th style="padding: 10px 16px; text-align: right; font-size: 10px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.08em; color: #6b7280; width: 110px;">Price</th>
        <th style="padding: 10px 16px; text-align: right; font-size: 10px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.08em; color: #6b7280; width: 110px;">Total</th>
      </tr>
    </thead>
    <tbody>
      ${lines}
    </tbody>
  </table>

  <div style="display: flex; justify-content: flex-end;">
    <div style="width: 260px;">
      <div style="display: flex; justify-content: space-between; padding: 6px 0; font-size: 13px;">
        <span style="color: #6b7280;">Subtotal</span>
        <span style="color: #374151; font-variant-numeric: tabular-nums;">$${centsToDollars(invoice.subtotal_cents)}</span>
      </div>
      <div style="display: flex; justify-content: space-between; padding: 6px 0; font-size: 13px;">
        <span style="color: #6b7280;">Tax (${invoice.tax_rate}%)</span>
        <span style="color: #374151; font-variant-numeric: tabular-nums;">$${centsToDollars(invoice.tax_cents)}</span>
      </div>
      <div style="display: flex; justify-content: space-between; padding: 10px 16px; margin-top: 8px; background: #2563eb; border-radius: 8px; font-size: 15px; font-weight: 700; color: #fff;">
        <span>Total</span>
        <span style="font-variant-numeric: tabular-nums;">$${centsToDollars(invoice.total_cents)}</span>
      </div>
    </div>
  </div>

  ${
    invoice.notes
      ? `
  <div style="margin-top: 32px;">
    <div style="font-size: 10px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.08em; color: #9ca3af; margin-bottom: 6px;">Notes</div>
    <div style="font-size: 12px; color: #6b7280; white-space: pre-line; background: #f9fafb; border: 1px solid #f3f4f6; border-radius: 8px; padding: 12px 16px;">${escapeHtml(invoice.notes)}</div>
  </div>`
      : ""
  }

  ${footerHtml()}
</div>
</body>
</html>`;
}

function classicTemplate({
  invoice,
  profile,
  logoBase64,
}: {
  invoice: InvoiceDetail;
  profile: BusinessProfile;
  logoBase64?: string;
}): string {
  const addr = fullAddress(profile);
  const lines = invoice.lines
    .sort((a, b) => a.sort_order - b.sort_order)
    .map(
      (l) => `
      <tr>
        <td style="padding: 8px 12px; border-bottom: 1px solid #d1d5db; font-size: 13px; color: #1f2937;">${escapeHtml(l.description)}</td>
        <td style="padding: 8px 12px; border-bottom: 1px solid #d1d5db; text-align: right; font-size: 13px; color: #4b5563; font-variant-numeric: tabular-nums;">${l.quantity}</td>
        <td style="padding: 8px 12px; border-bottom: 1px solid #d1d5db; text-align: right; font-size: 13px; color: #4b5563; font-variant-numeric: tabular-nums;">$${centsToDollars(l.unit_price_cents)}</td>
        <td style="padding: 8px 12px; border-bottom: 1px solid #d1d5db; text-align: right; font-size: 13px; color: #1f2937; font-weight: 600; font-variant-numeric: tabular-nums;">$${centsToDollars(l.total_cents)}</td>
      </tr>`,
    )
    .join("");

  const logoImg = logoBase64
    ? `<img src="${logoBase64}" alt="Logo" style="max-width: 120px; max-height: 48px; object-fit: contain;" />`
    : "";

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title> </title>
<style>
  ${printPageCss()}
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: Georgia, 'Times New Roman', serif; color: #1f2937; background: #fff; }
</style>
</head>
<body>
<div style="max-width: 800px; margin: 0 auto; padding: 40px 0;">
  <div style="border: 2px solid #1f2937; padding: 32px;">
    <div style="display: flex; justify-content: space-between; align-items: flex-start; padding-bottom: 20px; border-bottom: 2px solid #1f2937;">
      <div>
        ${logoImg ? `<div style="margin-bottom: 8px;">${logoImg}</div>` : ""}
        <div style="font-size: 20px; font-weight: 700; color: #1f2937;">${escapeHtml(profile.name)}</div>
        ${addr ? `<div style="font-size: 11px; color: #6b7280; margin-top: 4px; font-family: system-ui, sans-serif;">${escapeHtml(addr)}</div>` : ""}
        ${profile.email ? `<div style="font-size: 11px; color: #6b7280; margin-top: 2px; font-family: system-ui, sans-serif;">${escapeHtml(profile.email)}</div>` : ""}
        ${profile.phone ? `<div style="font-size: 11px; color: #6b7280; margin-top: 2px; font-family: system-ui, sans-serif;">${escapeHtml(profile.phone)}</div>` : ""}
      </div>
      <div style="text-align: right;">
        <div style="font-size: 24px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.08em; color: #1f2937;">${escapeHtml(invoice.invoice_type)}</div>
        <div style="font-size: 13px; color: #6b7280; margin-top: 4px; font-family: system-ui, sans-serif;">${escapeHtml(invoice.invoice_number)}</div>
        <div style="display: inline-block; margin-top: 6px; padding: 2px 8px; border: 1px solid ${invoice.status === "paid" ? "#166534" : invoice.status === "overdue" ? "#991b1b" : "#374151"}; color: ${invoice.status === "paid" ? "#166534" : invoice.status === "overdue" ? "#991b1b" : "#374151"}; font-size: 10px; font-weight: 600; text-transform: uppercase; font-family: system-ui, sans-serif;">${statusLabel(invoice.status)}</div>
      </div>
    </div>

    <div style="display: flex; justify-content: space-between; margin: 24px 0;">
      <div>
        <div style="font-size: 9px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.1em; color: #6b7280; margin-bottom: 6px; font-family: system-ui, sans-serif;">Bill To</div>
        <div style="font-size: 14px; font-weight: 600; color: #1f2937;">${escapeHtml(invoice.client_name)}</div>
        ${invoice.client_email ? `<div style="font-size: 11px; color: #6b7280; margin-top: 2px; font-family: system-ui, sans-serif;">${escapeHtml(invoice.client_email)}</div>` : ""}
        ${invoice.client_address ? `<div style="font-size: 11px; color: #6b7280; margin-top: 2px; white-space: pre-line; font-family: system-ui, sans-serif;">${escapeHtml(invoice.client_address)}</div>` : ""}
      </div>
      <div style="text-align: right; font-family: system-ui, sans-serif;">
        <div style="margin-bottom: 6px;">
          <span style="font-size: 9px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.1em; color: #6b7280;">Issue Date</span><br/>
          <span style="font-size: 13px; color: #1f2937;">${formatDate(invoice.issue_date)}</span>
        </div>
        ${
          invoice.due_date
            ? `<div>
          <span style="font-size: 9px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.1em; color: #6b7280;">Due Date</span><br/>
          <span style="font-size: 13px; color: ${invoice.status === "overdue" ? "#dc2626" : "#1f2937"}; font-weight: ${invoice.status === "overdue" ? "600" : "400"};">${formatDate(invoice.due_date)}</span>
        </div>`
            : ""
        }
      </div>
    </div>

    <table style="width: 100%; border-collapse: collapse; margin-bottom: 24px;">
      <thead>
        <tr style="background: #1f2937;">
          <th style="padding: 8px 12px; text-align: left; font-size: 9px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.1em; color: #fff; font-family: system-ui, sans-serif;">Description</th>
          <th style="padding: 8px 12px; text-align: right; font-size: 9px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.1em; color: #fff; width: 70px; font-family: system-ui, sans-serif;">Qty</th>
          <th style="padding: 8px 12px; text-align: right; font-size: 9px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.1em; color: #fff; width: 100px; font-family: system-ui, sans-serif;">Price</th>
          <th style="padding: 8px 12px; text-align: right; font-size: 9px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.1em; color: #fff; width: 100px; font-family: system-ui, sans-serif;">Total</th>
        </tr>
      </thead>
      <tbody>
        ${lines}
      </tbody>
    </table>

    <div style="display: flex; justify-content: flex-end;">
      <div style="width: 240px; border: 1px solid #d1d5db;">
        <div style="display: flex; justify-content: space-between; padding: 8px 12px; font-size: 12px; font-family: system-ui, sans-serif;">
          <span style="color: #6b7280;">Subtotal</span>
          <span style="color: #374151; font-variant-numeric: tabular-nums;">$${centsToDollars(invoice.subtotal_cents)}</span>
        </div>
        <div style="display: flex; justify-content: space-between; padding: 8px 12px; border-top: 1px solid #e5e7eb; font-size: 12px; font-family: system-ui, sans-serif;">
          <span style="color: #6b7280;">Tax (${invoice.tax_rate}%)</span>
          <span style="color: #374151; font-variant-numeric: tabular-nums;">$${centsToDollars(invoice.tax_cents)}</span>
        </div>
        <div style="display: flex; justify-content: space-between; padding: 10px 12px; background: #1f2937; font-size: 14px; font-weight: 700; color: #fff; font-family: system-ui, sans-serif;">
          <span>Total</span>
          <span style="font-variant-numeric: tabular-nums;">$${centsToDollars(invoice.total_cents)}</span>
        </div>
      </div>
    </div>

    ${
      invoice.notes
        ? `
    <div style="margin-top: 24px;">
      <div style="font-size: 9px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.1em; color: #6b7280; margin-bottom: 6px; font-family: system-ui, sans-serif;">Notes</div>
      <div style="font-size: 12px; color: #4b5563; white-space: pre-line; border: 1px solid #e5e7eb; border-radius: 4px; padding: 12px; font-family: system-ui, sans-serif;">${escapeHtml(invoice.notes)}</div>
    </div>`
        : ""
    }
  </div>

  ${footerHtml()}
</div>
</body>
</html>`;
}

function minimalTemplate({
  invoice,
  profile,
  logoBase64,
}: {
  invoice: InvoiceDetail;
  profile: BusinessProfile;
  logoBase64?: string;
}): string {
  const addr = fullAddress(profile);
  const sortedLines = [...invoice.lines].sort((a, b) => a.sort_order - b.sort_order);
  const lines = sortedLines
    .map(
      (l, i) => `
      <tr style="background: ${i % 2 === 0 ? "#fff" : "#f9fafb"};">
        <td style="padding: 10px 0; font-size: 13px; color: #1f2937;">${escapeHtml(l.description)}</td>
        <td style="padding: 10px 0; text-align: right; font-size: 13px; color: #9ca3af; font-variant-numeric: tabular-nums;">${l.quantity}</td>
        <td style="padding: 10px 0; text-align: right; font-size: 13px; color: #9ca3af; font-variant-numeric: tabular-nums;">$${centsToDollars(l.unit_price_cents)}</td>
        <td style="padding: 10px 0; text-align: right; font-size: 13px; color: #1f2937; font-weight: 500; font-variant-numeric: tabular-nums;">$${centsToDollars(l.total_cents)}</td>
      </tr>`,
    )
    .join("");

  const logoImg = logoBase64
    ? `<img src="${logoBase64}" alt="Logo" style="max-width: 100px; max-height: 40px; object-fit: contain;" />`
    : "";

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title> </title>
<style>
  ${printPageCss()}
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: #111827; background: #fff; }
</style>
</head>
<body>
<div style="max-width: 680px; margin: 0 auto; padding: 60px 0;">
  <div style="text-align: center; margin-bottom: 48px;">
    ${logoImg ? `<div style="margin-bottom: 12px;">${logoImg}</div>` : ""}
    <div style="font-size: 26px; font-weight: 300; color: #111827; letter-spacing: 0.04em;">${escapeHtml(profile.name)}</div>
    ${addr ? `<div style="font-size: 11px; color: #9ca3af; margin-top: 4px;">${escapeHtml(addr)}</div>` : ""}
    <div style="font-size: 11px; color: #9ca3af; margin-top: 2px;">
      ${[profile.email, profile.phone]
        .filter(Boolean)
        .map((s) => escapeHtml(s as string))
        .join(" &middot; ")}
    </div>
  </div>

  <div style="text-align: center; margin-bottom: 40px;">
    <div style="font-size: 11px; text-transform: uppercase; letter-spacing: 0.12em; color: #9ca3af; margin-bottom: 4px;">${escapeHtml(invoice.invoice_type)} ${escapeHtml(invoice.invoice_number)}</div>
    <div style="display: inline-block; padding: 2px 10px; font-size: 10px; font-weight: 500; text-transform: uppercase; letter-spacing: 0.06em; color: ${invoice.status === "paid" ? "#166534" : invoice.status === "overdue" ? "#991b1b" : "#6b7280"};">${statusLabel(invoice.status)}</div>
  </div>

  <div style="display: flex; justify-content: space-between; margin-bottom: 40px; padding: 0 20px;">
    <div>
      <div style="font-size: 9px; text-transform: uppercase; letter-spacing: 0.12em; color: #9ca3af; margin-bottom: 6px;">Billed to</div>
      <div style="font-size: 14px; font-weight: 500; color: #111827;">${escapeHtml(invoice.client_name)}</div>
      ${invoice.client_email ? `<div style="font-size: 12px; color: #9ca3af; margin-top: 2px;">${escapeHtml(invoice.client_email)}</div>` : ""}
      ${invoice.client_address ? `<div style="font-size: 12px; color: #9ca3af; margin-top: 2px; white-space: pre-line;">${escapeHtml(invoice.client_address)}</div>` : ""}
    </div>
    <div style="text-align: right;">
      <div style="margin-bottom: 8px;">
        <div style="font-size: 9px; text-transform: uppercase; letter-spacing: 0.12em; color: #9ca3af;">Date Issued</div>
        <div style="font-size: 13px; color: #111827; margin-top: 2px;">${formatDate(invoice.issue_date)}</div>
      </div>
      ${
        invoice.due_date
          ? `<div>
        <div style="font-size: 9px; text-transform: uppercase; letter-spacing: 0.12em; color: #9ca3af;">Date Due</div>
        <div style="font-size: 13px; color: ${invoice.status === "overdue" ? "#dc2626" : "#111827"}; margin-top: 2px;">${formatDate(invoice.due_date)}</div>
      </div>`
          : ""
      }
    </div>
  </div>

  <table style="width: 100%; border-collapse: collapse; margin-bottom: 32px;">
    <thead>
      <tr style="border-bottom: 1px solid #e5e7eb;">
        <th style="padding: 8px 0; text-align: left; font-size: 9px; font-weight: 500; text-transform: uppercase; letter-spacing: 0.12em; color: #9ca3af;">Description</th>
        <th style="padding: 8px 0; text-align: right; font-size: 9px; font-weight: 500; text-transform: uppercase; letter-spacing: 0.12em; color: #9ca3af; width: 60px;">Qty</th>
        <th style="padding: 8px 0; text-align: right; font-size: 9px; font-weight: 500; text-transform: uppercase; letter-spacing: 0.12em; color: #9ca3af; width: 90px;">Price</th>
        <th style="padding: 8px 0; text-align: right; font-size: 9px; font-weight: 500; text-transform: uppercase; letter-spacing: 0.12em; color: #9ca3af; width: 90px;">Amount</th>
      </tr>
    </thead>
    <tbody>
      ${lines}
    </tbody>
  </table>

  <div style="display: flex; justify-content: flex-end;">
    <div style="width: 220px;">
      <div style="display: flex; justify-content: space-between; padding: 6px 0; font-size: 13px;">
        <span style="color: #9ca3af;">Subtotal</span>
        <span style="color: #6b7280; font-variant-numeric: tabular-nums;">$${centsToDollars(invoice.subtotal_cents)}</span>
      </div>
      <div style="display: flex; justify-content: space-between; padding: 6px 0; font-size: 13px;">
        <span style="color: #9ca3af;">Tax (${invoice.tax_rate}%)</span>
        <span style="color: #6b7280; font-variant-numeric: tabular-nums;">$${centsToDollars(invoice.tax_cents)}</span>
      </div>
      <div style="display: flex; justify-content: space-between; padding: 10px 0; margin-top: 8px; border-top: 2px solid #111827; font-size: 16px; font-weight: 600;">
        <span>Total</span>
        <span style="font-variant-numeric: tabular-nums;">$${centsToDollars(invoice.total_cents)}</span>
      </div>
    </div>
  </div>

  ${
    invoice.notes
      ? `
  <div style="margin-top: 40px; padding: 0 20px;">
    <div style="font-size: 9px; text-transform: uppercase; letter-spacing: 0.12em; color: #9ca3af; margin-bottom: 6px;">Notes</div>
    <div style="font-size: 12px; color: #6b7280; white-space: pre-line;">${escapeHtml(invoice.notes)}</div>
  </div>`
      : ""
  }

  ${footerHtml()}
</div>
</body>
</html>`;
}
