mod ai;
mod commands;
mod db;
mod domain;
mod error;
pub mod reports;
mod state;

use state::AppState;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_shell::init())
        .plugin(tauri_plugin_updater::Builder::new().build())
        .manage(AppState::new())
        .invoke_handler(tauri::generate_handler![
            commands::unlock::ping,
            commands::unlock::unlock_app,
            commands::unlock::lock_app,
            commands::unlock::is_unlocked,
            commands::clients::list_clients,
            commands::clients::create_client,
            commands::clients::switch_client,
            commands::clients::get_active_client_id,
            commands::clients::set_active_client_pref,
            commands::clients::get_active_client_pref,
            commands::clients::update_client,
            commands::clients::archive_client,
            commands::accounts::list_accounts,
            commands::accounts::get_account_balance,
            commands::accounts::create_account,
            commands::accounts::update_account,
            commands::accounts::toggle_account_active,
            commands::transactions::list_transactions,
            commands::transactions::create_transaction,
            commands::transactions::update_transaction,
            commands::transactions::delete_transaction,
            reports::pnl::get_pnl,
            reports::balance_sheet::get_balance_sheet,
            reports::balance_sheet::get_balance_sheet_cumulative,
            reports::cash_flow::get_cash_flow,
            commands::dashboard::get_dashboard_stats,
            commands::dashboard::get_net_cash_trend,
            commands::dashboard::get_top_categories,
            commands::dashboard::get_deductible_expenses,
            commands::period::report_period_for,
            commands::print_helper::print_html,
            commands::export::export_transactions_csv,
            commands::export::export_report_csv,
            commands::export::save_csv_file,
            commands::backup::backup_database,
            commands::backup::restore_database,
            commands::settings::get_settings,
            commands::settings::save_settings,
            commands::files::list_dir_files,
            ai::ollama::ollama_health,
            ai::ollama::check_ai_health_with_url,
            ai::ollama::suggest_category,
            ai::ollama::nl_query,
            ai::glmocr::glmocr_available,
            ai::glmocr::glmocr_status,
            ai::glmocr::scan_receipt,
            ai::lmstudio::lmstudio_health,
            ai::lmstudio::lmstudio_list_models,
            ai::lmstudio::ollama_list_models,
            ai::lmstudio::ollama_health_url,
            commands::invoices::list_invoices,
            commands::invoices::get_invoice,
            commands::invoices::create_invoice,
            commands::invoices::update_invoice,
            commands::invoices::delete_invoice,
            commands::invoices::update_invoice_status,
            commands::updater::check_for_updates,
            commands::updater::get_app_version,
            commands::updater::download_update,
            commands::updater::install_update,
            commands::updater::pull_latest_commits,
            commands::documents::list_documents,
            commands::documents::add_document,
            commands::documents::delete_document,
            commands::documents::update_document,
            commands::client_export::export_client_documents,
            commands::client_export::export_all_clients_documents,
            commands::evidence::store_evidence,
            commands::evidence::get_evidence,
            commands::evidence::list_evidence,
            commands::evidence::delete_evidence,
            commands::drafts::create_draft,
            commands::drafts::update_draft,
            commands::drafts::list_drafts,
            commands::drafts::approve_draft,
            commands::drafts::reject_draft,
            commands::drafts::bulk_approve_drafts,
            commands::drafts::bulk_reject_drafts,
            commands::chat::send_chat_message,
            commands::chat::send_chat_message_stream,
            commands::chat::get_chat_history,
            commands::chat::clear_chat_history,
            commands::business_profile::get_business_profile,
            commands::business_profile::save_business_profile,
            commands::tax_news::fetch_tax_news,
            commands::tax_news::refresh_tax_news,
            commands::logger::log_error,
            commands::logger::get_error_log_path,
            commands::csv_import::preview_csv,
            commands::csv_import::import_csv,
            commands::recurring::list_recurring,
            commands::recurring::create_recurring,
            commands::recurring::update_recurring,
            commands::recurring::delete_recurring,
            commands::recurring::run_due_recurring,
            commands::mileage::create_mileage_log,
            commands::mileage::list_mileage_logs,
            commands::mileage::delete_mileage_log,
            commands::mileage::get_mileage_summary,
            commands::mileage::get_irs_mileage_rate,
            commands::mileage::get_mileage_deduction_total,
            commands::schedule_c::list_schedule_c_mappings,
            commands::schedule_c::upsert_schedule_c_mapping,
            commands::schedule_c::delete_schedule_c_mapping,
            commands::schedule_c::calculate_schedule_c_summary,
            commands::vendors_1099::list_vendors,
            commands::vendors_1099::create_vendor,
            commands::vendors_1099::update_vendor,
            commands::vendors_1099::delete_vendor,
            commands::vendors_1099::record_contractor_payment,
            commands::vendors_1099::list_contractor_payments,
            commands::vendors_1099::generate_1099_nec,
            commands::vendors_1099::list_generated_1099_nec,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
